### ISSUE TITLE
Ditto-centric Stack Trace

### ISSUE THREAD

**Issue by Nicholas-Westby** [umco/umbraco-ditto#236]
Every now and then, I'll get an exception thrown from some Ditto processor, but the exception message usually pops up in Visual Studio from the line that called the initial mapping (e.g., `var mapped = Model.Content.As<Typical>();`).

That makes it pretty challenging to figure out where the error actually came from. I typically resort to process elimination to try and figure out where the error was (e.g., by deleting Ditto processors from properties), and in really dire circumstances by integrating the Ditto source code with a project to get a more accurate exception breakpoint. This is cumbersome.

It would be nice if when Ditto encountered an exception during the mapping process, it wrapped the exception and threw a new exception with one that has a sort of stack trace. Rather than an actual stack trace though, I'm imagining this stack trace would actually show the Ditto processors that were run, along with the class and property they were run on. This stack trace might even be in the form of a string message that simulates what the class/property/attributes look like:

```cs
public class MyWidget // This class is in c:\r\solution\project\folder\MyWidget.cs
{
    [UmbracoProperty]
    [GetImages]
    [FirstItem] <----------------------------------------- Error here.
    [WithCrop("Square")]
    public string Image { get; set; }
}
```

**Comment by Nicholas-Westby** [comment]
FYI, this is still on my mind, but I don't expect to have time for it for weeks or months. If somebody else has time, definitely feel free to step in and make some magic happen.

**Comment by leekelleher** [comment]
@Nicholas-Westby 3+ years later, thanks again for the suggestion, but time for me say that the Ditto ship has sailed - I'll close this off. _(We're in Umbraco v9 land now. 😎)_
